### ISSUE TITLE
More readable readme

### ISSUE THREAD

**Issue by perrycate** [TheGuyWithTheFace/FalconHoster#3]
Could use some markdown or something to spruce it up a bit

**Comment by kevinrabinovich** [comment]
Fixed: https://github.com/kevinrabinovich/FalconHoster/commit/072f73f6f4216f26b9ec6db885bb0c46ad51a096.

**Comment by kevinrabinovich** [comment]
@TheGuyWithTheFace (Close this issue? I can't because I'm not a collaborator.)
