### ISSUE TITLE
Copy generated File URL to clipboard

### ISSUE THREAD

**Issue by kevinrabinovich** [TheGuyWithTheFace/FalconHoster#5]
I think it can be done with Javascript, and Flash can be used as a fallback.

**Comment by perrycate** [comment]
What's the advantage of doing so?

**Comment by kevinrabinovich** [comment]
At first, I was thinking for some reason the ability to quickly copy / paste this into a chat or something, but that seems like an unlikely scenario. There could just be a copy button instead that does this, instead of having that be done automatically. Or it could be toggled.

**Comment by perrycate** [comment]
...Or... copy the link in the browser?
Besides, hopefully no one is running this on a public server, so it would just be accessible to those on the local network anyway.
